export const affirmations = [
    "You are capable of achieving your health goals!",
    "You deserve to feel vibrant and energetic!",
    "Every healthy choice you make today brings you closer to your goals!",
    "Your body is strong and resilient.",
    "You have the power to create positive changes in your life.",
    "Your health and well-being are important and deserve your attention.",
    "You are worthy of love and care, especially from yourself.",
    "You are in control of your health and happiness.",
    "You have the strength to overcome any challenges you face.",
    "You are surrounded by love and support.",
    "You are becoming healthier and happier every day.",
    "You are worthy of self-care and self-love.",
    "You have the courage to prioritize your health and well-being.",
    "You are making progress, even if it's not always visible.",
    "Your body is your home, treat it with kindness and respect.",
    "You have the power to make positive changes in your life.",
    "You are resilient and can bounce back from setbacks.",
    "You are worthy of respect and admiration.",
    "You are worthy of happiness and fulfillment.",
    "You have the strength to overcome any obstacles.",
    "Your health and well-being are top priorities.",
    "You are capable of achieving your dreams.",
    "You are deserving of good health and happiness.",
    "You have the ability to create the life you desire.",
    "You are worthy of all the good things life has to offer.",
    "You are surrounded by love and support.",
    "You are capable of achieving anything you set your mind to.",
    "You are worthy of success and abundance.",
    "You are deserving of love, happiness, and good health.",
    "You are a unique and valuable individual.",
    "You are worthy of respect and admiration from others.",
    "You have the strength and determination to overcome any challenges.",
    "You are worthy of all the good things life has to offer.",
    "You are capable of achieving greatness.",
    "You are deserving of love and happiness.",
    "You are worthy of all the good things life has to offer.",
    "You are capable of overcoming any obstacles.",
    "You have the power to create positive change in your life.",
    "You are worthy of love and acceptance.",
    "You are worthy of all the love and happiness in the world.",
    "You are capable of achieving your dreams and goals.",
];